### ISSUE TITLE
Configure flake8 via pyproject.toml

### ISSUE THREAD

**Issue by dciborow** [microsoft/vscode-flake8#135]
# Issue description
`Flake8` [does not](https://github.com/PyCQA/flake8/issues/234) natively support configuration via pyproject.toml. The flake8 plugin 'flake8-pyproject' enables this functionality. It adds a configuration '--config-toml' to flake8. By default, it will look for flake8 configuration in the pyproject.toml. If the section "tools.flake8" is missing, then it will look for .flake8. If both the .flake8 and tools.project is present in the pyproject.toml, the pyproject.toml will be used.

Enabling configuration of flake8 via pyproject.toml lets users consolidate all of the different linter configurations into one spot. This plugin provides the minimum functionality and is not pinned to any particular version of flake8. While there are many packages on pypi that try to provide pyproject support for flake8, this is the simplest and most effective.
# Installation
You can install the 'flake8-pyproject' plugin using pip:

```sh
pip install flake8-pyproject
```
# Example configuration
Here is an example configuration for flake8 using pyproject.toml:

```toml
[tool.flake8]
# Check that this is aligned with your other tools like Black
max-line-length = 120
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__"
]
# Use extend-ignore to add to already ignored checks which are anti-patterns like W503.
extend-ignore = [
    # PEP 8 recommends to treat : in slices as a binary operator with the lowest priority, and to leave an equal
    # amount of space on either side, except if a parameter is omitted (e.g. ham[1 + 1 :]).
    # This behaviour may raise E203 whitespace before ':' warnings in style guide enforcement tools like Flake8.
    # Since E203 is not PEP 8 compliant, we tell Flake8 to ignore this warning.
    # https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices    
    "E203"
]
```

# Benefits
Using the 'flake8-pyproject' plugin provides the following benefits:

- Simplified configuration of flake8 using pyproject.toml
- Consolidation of all linter configurations into one spot
- Not pinned to any particular version of flake8
- Does not impact users who are still using .flake8, as it falls back to the .flake8 file if the pyproject.toml configuration is missing
- Ability to use the --config-toml argument to point to the location of the pyproject.toml file, even if it is not in the project root directory. For example:
`flake8.args=["--config-toml=/path/to/pyproject.toml"`
This can be useful if you have a complex project structure where the pyproject.toml file is located in a subdirectory or a parent directory of the project root directory.
